Updated action for KO

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -71,28 +71,155 @@ inputs:
     description: 'OS version on which splunk will be spinned for scripted input'
     required: false
     default: 'latest'
-
 outputs:
-  workflow-name: # id of output
-    description: 'Name of workflow triggered'
+  random-number:
+    description: "Random number"
+    value: ${{ steps.random-number-generator.outputs.random-number }}
 runs:
-  using: 'docker'
-  image: 'Dockerfile'
-  args:
-    - ${{ inputs.workflow-tmpl-name }}
-    - ${{ inputs.workflow-template-ns }}
-    - ${{ inputs.delay-destroy }}
-    - ${{ inputs.addon-url }}
-    - ${{ inputs.job-name }}
-    - ${{ inputs.splunk }}
-    - ${{ inputs.test-type }}
-    - ${{ inputs.test-args }}
-    - ${{ inputs.labels }}
-    - ${{ inputs.addon-name }}
-    - ${{ inputs.vendor-version }}
-    - ${{ inputs.sc4s-version }}
-    - ${{ inputs.install-java }}
-    - ${{ inputs.sc4s-docker-registry }}
-    - ${{ inputs.os-name }}
-    - ${{ inputs.os-version }}
+  using: "composite"
+  steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: recursive
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+    - name: Read secrets from AWS Secrets Manager into environment variables
+      id: get-argo-token
+      run: |
+        ARGO_TOKEN=$(aws secretsmanager get-secret-value --secret-id ta-github-workflow-automation-token | jq -r '.SecretString')
+        echo "::set-output name=argo-token::$ARGO_TOKEN"
+    - name: create job name
+      id: create-job-name
+      shell: bash
+      run: |
+        RANDOM_STRING=$(head -3 /dev/urandom | tr -cd '[:lower:]' | cut -c -4)
+        JOB_NAME=${{ needs.setup.outputs.job-name }}-${RANDOM_STRING}
+        JOB_NAME=${JOB_NAME//TEST-TYPE/${{ env.TEST_TYPE }}}
+        JOB_NAME=${JOB_NAME//[_.]/-}
+        JOB_NAME=$(echo "$JOB_NAME" | tr '[:upper:]' '[:lower:]')
+        echo "::set-output name=job-name::$JOB_NAME"
 
+    - name: run-tests
+      id: run-tests
+      env:
+        ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
+      uses: splunk/wfe-test-runner-action@v1.6.1
+      with:
+        splunk: ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }}
+        test-type: ${{ env.TEST_TYPE }}
+        test-args: ""
+        job-name: ${{ steps.create-job-name.outputs.job-name }}
+        labels: ${{ needs.setup.outputs.labels }}
+        workflow-tmpl-name: ${{ needs.setup.outputs.argo-workflow-tmpl-name }}
+        workflow-template-ns: ${{ needs.setup.outputs.argo-namespace }}
+        delay-destroy: "No"
+        addon-url: ${{ needs.setup.outputs.addon-upload-path }}
+        addon-name: ${{ needs.setup.outputs.addon-name }}
+        sc4s-version: ${{ matrix.sc4s.version }}
+        sc4s-docker-registry: ${{ matrix.sc4s.docker_registry }}
+    - name: Check if pod was deleted
+      id: is-pod-deleted
+      if: always()
+      shell: bash
+      env:
+        ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
+      run: |
+        set -o xtrace
+        if argo watch ${{ steps.run-tests.outputs.workflow-name }} -n workflows | grep "pod deleted"; then
+          echo "::set-output name=retry-workflow::true"
+        fi
+    - name: Retrying workflow
+      id: retry-wf
+      shell: bash
+      env:
+        ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
+      if: always()
+      run: |
+        set -o xtrace
+        set +e
+        if [[ "${{ steps.is-pod-deleted.outputs.retry-workflow }}" == "true" ]]
+        then
+          WORKFLOW_NAME=$(argo resubmit -v -o json -n workflows "${{ steps.run-tests.outputs.workflow-name }}" | jq -r .metadata.name)
+          echo "::set-output name=workflow-name::$WORKFLOW_NAME"
+          argo logs --follow "${WORKFLOW_NAME}" -n workflows || echo "... there was an error fetching logs, the workflow is still in progress. please wait for the workflow to complete ..."
+        else
+          echo "No retry required"
+          argo wait "${{ steps.run-tests.outputs.workflow-name }}" -n workflows
+          argo watch "${{ steps.run-tests.outputs.workflow-name }}" -n workflows | grep "test-addon"
+        fi
+    - name: check if workflow completed
+      env:
+        ARGO_TOKEN: ${{ steps.get-argo-token.outputs.argo-token }}
+      shell: bash
+      if: always()
+      run: |
+        set +e
+        # shellcheck disable=SC2157
+        if [ -z "${{ steps.retry-wf.outputs.workflow-name }}" ]; then
+          WORKFLOW_NAME=${{ steps.run-tests.outputs.workflow-name }}
+        else
+          WORKFLOW_NAME="${{ steps.retry-wf.outputs.workflow-name }}"
+        fi
+        ARGO_STATUS=$(argo get "${WORKFLOW_NAME}" -n workflows -o json | jq -r '.status.phase')
+        echo "Status of workflow:" "$ARGO_STATUS"
+        while [ "$ARGO_STATUS" == "Running"  ] || [ "$ARGO_STATUS" == "Pending" ]
+        do
+            echo "... argo Workflow ${WORKFLOW_NAME} is running, waiting for it to complete."
+            argo wait "${WORKFLOW_NAME}" -n workflows || true
+            ARGO_STATUS=$(argo get "${WORKFLOW_NAME}" -n workflows -o json | jq -r '.status.phase')
+        done
+    - name: pull artifacts from s3 bucket
+      if: always()
+      run: |
+        echo "pulling artifacts"
+        aws s3 cp s3://${{ needs.setup.outputs.s3-bucket }}/artifacts-${{ steps.create-job-name.outputs.job-name }}/${{ steps.create-job-name.outputs.job-name }}.tgz ${{ needs.setup.outputs.directory-path }}/
+        tar -xf ${{ needs.setup.outputs.directory-path }}/${{ steps.create-job-name.outputs.job-name }}.tgz -C ${{ needs.setup.outputs.directory-path }}
+    - name: pull logs from s3 bucket
+      if: always()
+      run: |
+        # shellcheck disable=SC2157
+        if [ -z "${{ steps.retry-wf.outputs.workflow-name }}" ]; then
+          WORKFLOW_NAME=${{ steps.run-tests.outputs.workflow-name }}
+        else
+          WORKFLOW_NAME="${{ steps.retry-wf.outputs.workflow-name }}"
+        fi
+        echo "pulling logs"
+        mkdir -p ${{ needs.setup.outputs.directory-path }}/argo-logs
+        aws s3 cp s3://${{ needs.setup.outputs.s3-bucket }}/${WORKFLOW_NAME}/ ${{ needs.setup.outputs.directory-path }}/argo-logs/ --recursive
+    - uses: actions/upload-artifact@v3
+      if: always()
+      with:
+        name: archive splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ env.TEST_TYPE }} tests artifacts
+        path: |
+          ${{ needs.setup.outputs.directory-path }}/test-results
+    - uses: actions/upload-artifact@v3
+      if: always()
+      with:
+        name: archive splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ env.TEST_TYPE }} tests logs
+        path: |
+          ${{ needs.setup.outputs.directory-path }}/argo-logs
+    - name: Upload cim-compliance-report for ${{ matrix.splunk.version }}
+      uses: actions/upload-artifact@v3
+      if: ${{ matrix.splunk.islatest == true }}
+      with:
+        name: cim-compliance-report
+        path: |
+          ${{ needs.setup.outputs.directory-path }}/test-results/cim-compliance-report.md
+    - name: Upload cim-field-report for ${{ matrix.splunk.version }}
+      uses: actions/upload-artifact@v3
+      if: ${{ matrix.splunk.islatest == true }}
+      with:
+        name: cim-field-report
+        path: |
+          ${{ needs.setup.outputs.directory-path }}/test-results/cim_field_report.json
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: always()
+      with:
+        name: splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ env.TEST_TYPE }} test report
+        path: "${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
+        reporter: java-junit
